### ISSUE TITLE
Developers Page Items

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#454]
In the call of 14.11, we consolidated the ideas on the developers page. We want to add the following to the tools:

- Affiliation: See #446 
- How up-to-date it is: Indication of maintenance status can be:
  - Latest release
  - Latest commit
  - A vague term like "In active development" or "In hiatus" or "Archived"
  - A shields.io shield from maintenance category: https://shields.io/badges/maintenance
- License: Ideally, this should not change often and can be submitted during the initial submission.
- Category: Like the current categories but also related to #323 
- Supported TD version: Whether it supports the mechanisms in 1.0, 1.1 or is more experimental and not exactly compliant.

In terms of redesign, we can have a big table view. See https://json-schema.org/implementations and https://www.w3.org/WAI/ER/tools/

Additionally, having this in markdown would be better to have a better experience for contributors. There should be a small guide explaining how to make contributions.

**Comment by egekorkan** [comment]
To start, we should collect the information above in a yaml file so that jekyll can auto generate the page (e.g. a table). JSON Schema implementations are collected at https://github.com/json-schema-org/website/blob/main/data/validator-libraries-modern.yml for example.

**Comment by egekorkan** [comment]
We can start with collecting the information in a YAML format so that it integrates to Jekyll. Below is the starting point:

```yaml
- name: MyName
  affiliation: MyAffiliation
  is-maintained: yes #or no
  update-year: 2023
  license: MIT
  td-version: ["1.0"] # ["1.0","1.1"] or null
  category: ["consumer","td-tooling","discovery"]
```
